services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookapi_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://book_user:book_password@db:5432/books_db
    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: bookapi_db
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U book_user -d books_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
